source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AYSwift_Example', :exclusive => true do
  pod "AYSwift", :path => "../"
end

target 'AYSwift_Tests', :exclusive => true do
  pod "AYSwift", :path => "../"

  pod 'Quick', '~> 0.3.1'
  pod 'Nimble'
  pod 'FBSnapshotTestCase', '2.0.4'
  # pod 'Nimble-Snapshots'
end
